### PR TITLE
feat!: change CVAL3 to CVDL4 for PRO components

### PR DESCRIPTION
**Pull request by tulioag**

### CODE REVIEW

**Comment by ZheSun88** [comment]
Remember the LICENSE file in the root of each pro components , for example https://github.com/vaadin/vaadin-flow-components/blob/fix/ctt/556_change_CVAL3_to_CVDL4/vaadin-board-flow-parent/LICENSE

**Comment by tomivirkki** [comment]
Note that an exclamation mark should be used in the (squashed) commit message to mark this as a "breaking change"

**Comment by alvarezguille** [comment]
[This comment](https://github.com/vaadin/testbench/pull/1276#pullrequestreview-522614083) also applies to this PR. License is not part of the package anymore and `licensing.txt distributed with this software` section should be removed.

**Review by manolo — APPROVED** [review]

**Review by manolo — DISMISSED** [review]
LICENSE files need update as Zhe pointed

**Comment by tulioag** [comment]
> Remember the LICENSE file in the root of each pro components , for example https://github.com/vaadin/vaadin-flow-components/blob/fix/ctt/556_change_CVAL3_to_CVDL4/vaadin-board-flow-parent/LICENSE

@ZheSun88  https://github.com/vaadin/vaadin-flow-components/pull/511/commits/64d5e213361b90d0e7823d9b3bd7d4535bc095ef

**Comment by tulioag** [comment]
> [This comment](https://github.com/vaadin/testbench/pull/1276#pullrequestreview-522614083) also applies to this PR. License is not part of the package anymore and `licensing.txt distributed with this software` section should be removed.

@alvarezguille https://github.com/vaadin/vaadin-flow-components/pull/511/commits/ece6b878b25611cdb531a4907dd71523e04212fe

**Review by ZheSun88 — APPROVED** [review]

**Review by manolo — APPROVED** [review]

**Review by alvarezguille — APPROVED** [review]
LGTM

**Pull request merged**
