### PR TITLE
feat: add "no-padding" theme variants to dialog component.

### PR DESCRIPTION
**Pull request by sosa-vaadin**

### CODE REVIEW

**Review by web-padawan — CHANGES_REQUESTED** [review]
Blocking this from merging until `master` branch is updated to Vaadin 20. @manolo @ZheSun88 FYI

**Comment by tomivirkki** [comment]
This should be rebased now and changed to use the newest Web Component version

**Comment by sosa-vaadin** [comment]
> This should be rebased now and changed to use the newest Web Component version

Done.

**Comment by ZheSun88** [comment]
@web-padawan  Master branch has been updated to 20-SNAPSHOT. this PR can be merged now

**Review by yuriy-fix — APPROVED** [review]

**Review by web-padawan — APPROVED** [review]

**Comment by tomivirkki** [comment]
> This should be rebased now and changed to use the newest Web Component version

@sosa-vaadin Master still uses [2.5.2](https://github.com/vaadin/vaadin-flow-components/blob/master/vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/GeneratedVaadinDialog.java#L56) which doesn't have the `no-padding` theme variant available. The version should be bumped to 3 alpha (release a new alpha if necessary).

**Pull request merged**
